name: commit

on: [push, pull_request]

jobs:
  bin:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Use env
      env:
        MY_SECRET_ENV: ${{ secrets.MY_SECRET }}
      run: echo "$MY_SECRET_ENV"

    - name: Use secret
      run: echo "${{ secrets.MY_SECRET }}"

    - name: Use printenv
      env:
        MY_SECRET_ENV: ${{ secrets.MY_SECRET }}
      run: printenv MY_SECRET_ENV

    - name: Pipe printenv
      env:
        MY_SECRET_ENV: ${{ secrets.MY_SECRET }}
      run: printenv MY_SECRET_ENV | echo "none"

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump Env context
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
      run: echo "$ENV_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
